import {createConstants} from '../utils';

export default createConstants(
  'NET_STATE_CHANGED',
  'REQUEST_STARTED',
  'REQUEST_COMPLETED',
  'REQUEST_FAIL',
  'LOGIN_SUCCESS',
  'LOGIN_FAILED',
  'LOGIN_PENDING',
  'FORGOT_SUCCESS',
  'FORGOT_FAILED',
  'FORGOT_PENDING',
  'RESET_PASSWORD_SUCCESS',
  'RESET_PASSWORD_FAILED',
  'RESET_PASSWORD_PENDING',
  'LOGOUT_SUCCESS',
  'LOGOUT_FAILED',
  'LOGOUT_PENDING',
  'FETCH_LOGIN_USER_DATA_SUCCESS',
  'FETCH_LOGIN_USER_DATA_FAILED',
  'FETCH_USER_STATE_DATA_PENDING',
  'FETCH_USER_STATE_DATA_SUCCESS',
  'FETCH_USER_STATE_DATA_FAILED',
  'FETCH_CITY_DATA_PENDING',
  'FETCH_CITY_DATA_SUCCESS',
  'FETCH_CITY_DATA_FAILED',
  'FETCH_USER_ROLE_PENDING',
  'FETCH_USER_ROLE_SUCCESS',
  'FETCH_USER_ROLE_FAILED',
  'SIGN_UP_PENDING',
  'SIGN_UP_SUCCESS',
  'SIGN_UP_FAILED',
  'PROFILE_PENDING',
  'FETCH_PROFILE_USER_DATA_FAILED',
  'FETCH_PROFILE_USER_DATA_SUCCESS',
  'RESET_STORE',
  'CHANGE_PASSWORD_PENDING',
  'CHANGE_PASSWORD_SUCCESS',
  'CHANGE_PASSWORD_FAILED',
  'FORGOT_PASSWORD_PENDING',
  'FORGOT_PASSWORD_SUCCESS',
  'FORGOT_PASSWORD_FAILED',
  'CHANGE_PASSWORD_RESET',

  //Sponsor data fetch Action data
  'FETCH_SPONSOR_PENDING',
  'FETCH_SPONSOR_SUCCESS',
  'FETCH_SPONSOR_FAILED',

  // Dashboard
  'FETCH_QUIZ_QUESTION_DATA_SUCCESS',
  'FETCH_QUIZ_QUESTION_DATA_FAILED',
  'FETCH_QUIZ_ANSWERED_QUESTION_DATA_SUCCESS',
  'FETCH_QUIZ_ANSWERED_QUESTION_DATA_FAILED',
  'FETCH_QUIZ_ANSWERED_QUESTION_DATA_IS_UPDATED',
  'FETCH_QUIZ_DATA_PENDING',
  'FETCH_QUIZ_ANSWERED_QUESTION_SCORE_DATA_SUCCESS',

  // GameSummary
  'FETCH_GAME_SUMMARY_DATA_SUCCESS',
  'FETCH_GAME_SUMMARY_DATA_FAILED',
  'FETCH_GAME_SUMMARY_DATA_PENDING',

  // Game Details
  'GAME_DETAIL_PENDING',
  'FETCH_GAME_DETAIL_DATA_FAILED',
  'FETCH_GAME_DETAIL_DATA_SUCCESS',

  //LeaderBoard
  'FETCH_LEADERBOARD_DATA_PENDING',
  'FETCH_LEADERBOARD_DATA_FAILED',
  'FETCH_LEADERBOARD_DATA_SUCCESS',
  'FETCH_LEADERBOARD_RANK_SCORE_DATA_SUCCESS',

  //Badages
  'USER_BADAGES_DATA_SUCCESS',
  'USER_BADAGES_DATA_FAILED',
);
